name: benchmate
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit
  - mmseqs2
  - fpocket
  - foldseek
  - folddisco
  - clustalo
  - blast
  - conda-forge::pgvector
  - conda-forge::rdkit-postgresql
  - viennarna
  - python=3.12
  - postgresql=18
  - pip
  - pip:
      - torch
      - torchvision
      - transformers
      - sentence-transformers
      - qwen_vl_utils
      - accelerate
      - requests
      - pandas==2.1.4
      - biopython
      - beautifulsoup4
      - SQLAlchemy==1.4.54
      - rdkit
      - biotite
      - alphagenome
      - model2vec
      - psycopg2-binary
      - bitsandbytes
      - chonkie[st]==0.3.0
      - lxml
      - pysam
      - pgvector
      - pydantic
      - xmltodict
      - kneed
      - paddleocr[all]
