name: benchmate
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge:tesseract=5.3.1
  - cuda-toolkit
  - mustang
  - mmseqs2
  - python=3.10
  - usalign
  - pip
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1

